defaultPortal: DEV

# Optionally set the default mode for all portals
defaultMode: publish

# Override default HTTP timeout in milliseconds
httpTimeout: 30000

# Disable usage tracking
allowUsageTracking: false

# List of portals that are intended to be used
portals:
  # Portal set up to use an API Key
  - name: DEV
    portalId: 123
    # Override mode for portal
    defaultMode: draft
    authType: apikey
    apiKey: d1234567-123e-7890-b123-aaa80164b4cb
  # Portal set up to use OAuth2
  - name: PROD
    portalId: 456
    authType: oauth2
    auth:
      clientId: d996372f-2b53-30d3-9c3b-4fdde4bce3a2
      clientSecret: f90a6248-fbc0-3b03-b0db-ec58c95e791
      scopes:
        - content
      tokenInfo:
        expiresAt: '2019-05-02T02:52:05.233Z'
        refreshToken: 84d22710-4cb7-5581-ba05-35f9945e5e8e
        accessToken: >-
          CJDVnLanLRICEQIYyLu8LyDh9E4opf1GMhkAxGuU5XN_O2O2QhX0khw7cwIkPkBRHye-OfIADgLBAAADAIADAAAAAAAAAAJCGQC8a5TlhtSU8T-2mVLxOBpxS18aM42oGKk
  - name: QA
    portalId: 101702799
    authType: usertoken
    userToken: >-
      By3Xx8o6Y616F-ORs7ErQl1Y2Vo2r28JxPi4UgJRInzsWs2-cJr5FOnnol12-9v_o7xMLXrA0wkaz_uKYp5oOB9XmS36mXvHPxAg2zLy9_dWYTgJE8uFU-u_2p0mg95XdJuIGQvs9HT
    auth:
      tokenInfo:
        accessToken: >-
          By3Xx8o6Y616F-ORs7ErQl1Y2Vo2r28JxPi4UgJRInzsWs2-cJr5FOnnol12-9v_o7xMLXrA0wkaz_uKYp5oOB9XmS36mXvHPxAg2zLy9_dWYTgJE8uFU-u_2p0mg95XdJuIGQvs9HT
        expiresAt: '2020-02-05T20:51:09.857Z'
