on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Use Node.js
      uses: actions/setup-node@v1
      with:
        node-version: 10.x
    - name: Install deps
      run: |
          yarn install
    - name: Force local package symlinks
      run: |
          yarn lerna link --force-local
    - name: Lint
      run: |
          yarn lint
    - name: Test
      run: |
          yarn test
    - name: Circular dependency check
      run: |
          yarn run madge --circular packages
