on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Report Status
      if: always()
      uses: ravsamhq/notify-slack-action@master
      with:
        status: ${{ job.status }}
        notify_when: 'failure'
      env:
        SLACK_WEBHOOK_URL: ${{ secrets.ACTION_MONITORING_SLACK }}
    - uses: actions/checkout@v1
    - name: Use Node.js
      uses: actions/setup-node@v1
      with:
        node-version: 10.x
    - name: Install Yarn
      run: npm install -g yarn
    - name: Install deps
      run: |
          yarn install
    - name: Install testing deps
      working-directory: ./acceptance-tests
      run: |
          yarn install
    - name: Bootstrap packages
      run: |
          yarn lerna bootstrap
    - name: Force local package symlinks
      run: |
          yarn lerna link --force-local
    - name: Verify package dependencies
      run: |
          yarn check-deps
    - name: Lint
      run: |
          yarn lint
    - name: Circular dependency check
      run: |
          yarn run madge --circular packages
    - name: Test
      run: |
          yarn test
    - name: Test-CLI
      working-directory: ./acceptance-tests
      run: |
          yarn test
