# This workflow will check for circular dependencies within the hubspot-cms-cli packages

name: Madge Circular Dependency Check

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  check-circular-deps:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js 10.x
      uses: actions/setup-node@v1
      with:
        node-version: 10.x
    - run: npm i -g madge
    - run: madge --circular packages
